### ISSUE TITLE
The link to demo app doesn't work

### ISSUE THREAD

**Issue by anatoly314** [bharatpatil/WhiteBoard#1]
Hi, 
link which you've provided to demo app doesn't work, is there any place where I can see how this app works?
Thank you.

**Comment by bharatpatil** [comment]
You can run it locally.

On Thursday 4 February 2016, Anatoly Tarnavsky notifications@github.com
wrote:

> Hi,
> link which you've provided to demo app doesn't work, is there any place
> where I can see how this app works?
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bharatpatil/WhiteBoard/issues/1.

## 

-- Bharathttp://www.digitoffee.com

DISCLAIMER
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This email and any files transmitted with it may or may not contain
Proprietary, Privileged and confidential information and/or information
protected by intellectual property rights and is only for the use of the
intended recipient of this message. If you are not the intended recipient
and by an addressing or transmission error, this mail has been misdirected
to you, please delete or destroy this and all copies of this message along
with the attachments.
You are hereby notified that any use, any form of reproduction,
dissemination, copying, disclosure, modification, distribution and/or
publication of this e-mail message, contents or its attachment (s) other
than by its intended recipient (s) is strictly prohibited. The recipient
should check this email and any attachments for the presence of viruses. I
accepts no liability for any damage caused by any virus transmitted through
this email.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by bharatpatil** [comment]
http://whiteboard-bharat.herokuapp.com/
